server:
  port: 3450

spring:
  datasource:
    url: jdbc:mysql://rm-f8zd1y18vy75i3v30vo.mysql.rds.aliyuncs.com:3306/bds?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: yulin
    password: Lp20000930
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: 113.45.133.84
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: jntff526
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 下划线转驼峰开启（如果字段名是下划线分隔的，则自动转换为驼峰命名）
    map-underscore-to-camel-case: true
    # SQL 打印配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 语句到控制台
  # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

