server:
  port: 3452

spring:
  application:
    name: bds-blockchain-service
  config:
    import:
      - nacos:common.yaml
      - nacos:blockchain.yaml
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      server-addr: 47.120.70.160:8848
      config:
        namespace: ${NACOS_NAMESPACE}
        file-extension: yaml
        refresh-enabled: false
        shared-configs:
          - data-id: common.yaml
          - data-id: blockchain.yaml
      discovery:
        namespace: ${NACOS_NAMESPACE}
